name: pull-request
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Git Pull Request Details
        run: |
          echo "Pull Request Creator: ${{ github.event.pull_request.user.login }}"
          echo "Pull Request title: ${{ github.event.pull_request.title }}"
          echo "Pull Request number: ${{ github.event.pull_request.number }}"
          echo "Pull Request url: ${{ github.event.pull_request.html_url }}"
          echo "Pull Request body: ${{ github.event.pull_request.body }}"
          echo "Assigned labels: " ${{ join(github.event.pull_request.labels.*.name) }}
          echo "Assignees: " ${{ join(github.event.pull_request.assignees.*.login) }}
      - name: Google Chat Notification
        run: |
          curl --location --request POST '${{ secrets.GOOGLECHAT }}' \
          --header 'Content-Type: application/json' \
          --data-raw '{
              "cardsV2":[
                {
                  "card":{
                    "header":{
                      "title":"${{ github.event.pull_request.user.login }}",
                      "subtitle":"Pull Request No: #${{ github.event.pull_request.number }}",
                      "imageUrl":"${{ github.event.pull_request.user.avatar }}",
                      "imageType":"CIRCLE"
                    },
                    "sections":[
                      {
                        "header":"${{ github.event.pull_request.title }}",
                        "widgets":[
                          {
                            "text":"${{ github.event.pull_request.body }}"
                          },
                          {
                            "buttonList":{
                              "buttons":[
                                {
                                  "textButton":{
                                    "text":"Open Pull Request",
                                    "color":{
                                      "red":1,
                                      "green":0,
                                      "blue":0,
                                      "alpha":1
                                    },
                                    "onClick":{
                                      "openLink":{
                                        "url":"${{ github.event.pull_request.html_url }}"
                                      }
                                    }
                                  }
                                }
                              ]
                            }
                          }
                        ]
                      }
                    ]
                  }
                }
              ]
          }'
